name: build
run-name: Build
on: [push]
jobs:
  build-win:
    env:
      CMAKE_PREFIX_PATH: "C:\\Qt\\6.3.2\\msvc2019_64\\lib\\cmake"
      PYTHONUNBUFFERED: "1"
    runs-on: windows-2022
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Install Qt
      - run: pip install aqtinstall==3.1.4
      - run: aqt install-qt windows desktop 6.3.2 win64_msvc2019_64 -O C:\Qt
      # Run the build script
      - run: python .\script\build-win.py
  build-linux:
    env:
      CMAKE_PREFIX_PATH: "~/.local/lib/qt/6.3.2/gcc_64"
      PYTHONUNBUFFERED: "1"
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Install Qt
      - run: sudo apt install ninja-build clang-tidy python-is-python3 python3-pip libgl1-mesa-dev libxkbcommon-x11-dev
      - run: pip install aqtinstall==3.1.4
      - run: ~/.local/bin/aqt install-qt linux desktop 6.3.2 gcc_64 -O ~/.local/lib/qt
      # Run the build script
      - run: python ./script/build-linux.py
